function main () {
    console.log('main');
    let table = [
        [  1,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   2],
        [  3,   4,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   5,   6,   7,   8,   9,  10],
        [ 11,  12,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,  13,  14,  15,  16,  17,  18],
        [ 19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36],
        [ 37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54],
        [ 55,  56,   0,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86],
        [ 87,  88,   0, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,   0],
        [  0,   0,  89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,   0],
    ];

    let elements = [
        //[id,  name, name, Gas/Liquid/Solid/Unknown, Metal/metalLoid/Non-metal/Unknown, radiative]
        [], // dummy
        [1,   'H',  '氫', 'g', 'n', false],
        [2,   'He', '氦', 'g', 'n', false],
        [3,   'Li', '鋰', 's', 'm', false],
        [4,   'Be', '鈹', 's', 'm', false],
        [5,   'B',  '硼', 's', 'l', false],
        [6,   'C',  '碳', 's', 'n', false],
        [7,   'N',  '氮', 'g', 'n', false],
        [8,   'O',  '氧', 'g', 'n', false],
        [9,   'F',  '氟', 'g', 'n', false],
        [10,  'Ne', '氖', 'g', 'n', false],
        [11,  'Na', '鈉', 's', 'm', false],
        [12,  'Mg', '鎂', 's', 'm', false],
        [13,  'Al', '鋁', 's', 'm', false],
        [14,  'Si', '矽', 's', 'l', false],
        [15,  'P',  '磷', 's', 'n', false],
        [16,  'S',  '硫', 's', 'n', false],
        [17,  'Cl', '氯', 'g', 'n', false],
        [18,  'Ar', '氬', 'g', 'n', false],
        [19,  'K',  '鉀', 's', 'm', false],
        [20,  'Ca', '鈣', 's', 'm', false],
        [21,  'Sc', '鈧', 's', 'm', false],
        [22,  'Ti', '鈦', 's', 'm', false],
        [23,  'V',  '釩', 's', 'm', false],
        [24,  'Cr', '鉻', 's', 'm', false],
        [25,  'Mn', '錳', 's', 'm', false],
        [26,  'Fe', '鐵', 's', 'm', false],
        [27,  'Co', '鈷', 's', 'm', false],
        [28,  'Ni', '鎳', 's', 'm', false],
        [29,  'Cu', '銅', 's', 'm', false],
        [30,  'Zn', '鋅', 's', 'm', false],
        [31,  'Ga', '鎵', 's', 'm', false],
        [32,  'Ge', '鍺', 's', 'l', false],
        [33,  'As', '砷', 's', 'l', false],
        [34,  'Se', '硒', 's', 'n', false],
        [35,  'Br', '溴', 'l', 'n', false],
        [36,  'Kr', '氪', 'g', 'n', false],
        [37,  'Rb', '銣', 's', 'm', false],
        [38,  'Sr', '鍶', 's', 'm', false],
        [39,  'Y',  '釔', 's', 'm', false],
        [40,  'Zr', '鋯', 's', 'm', false],
        [41,  'Nb', '鈮', 's', 'm', false],
        [42,  'Mo', '鉬', 's', 'm', false],
        [43,  'Tc', '鎝', 's', 'm', true],
        [44,  'Ru', '釕', 's', 'm', false],
        [45,  'Rh', '銠', 's', 'm', false],
        [46,  'Pd', '鈀', 's', 'm', false],
        [47,  'Ag', '銀', 's', 'm', false],
        [48,  'Cd', '鎘', 's', 'm', false],
        [49,  'In', '銦', 's', 'm', false],
        [50,  'Sn', '錫', 's', 'm', false],
        [51,  'Sb', '銻', 's', 'l', false],
        [52,  'Te', '碲', 's', 'l', false],
        [53,  'I',  '碘', 's', 'n', false],
        [54,  'Xe', '氙', 'g', 'n', false],
        [55,  'Cs', '銫', 's', 'm', false],
        [56,  'Ba', '鋇', 's', 'm', false],
        [57,  'La', '鑭', 's', 'm', false],
        [58,  'Ce', '鈰', 's', 'm', false],
        [59,  'Pr', '鐠', 's', 'm', false],
        [60,  'Nd', '釹', 's', 'm', false],
        [61,  'Pm', '鉕', 's', 'm', true],
        [62,  'Sm', '釤', 's', 'm', false],
        [63,  'Eu', '銪', 's', 'm', false],
        [64,  'Gd', '釓', 's', 'm', false],
        [65,  'Tb', '鋱', 's', 'm', false],
        [66,  'Dy', '鏑', 's', 'm', false],
        [67,  'Ho', '鈥', 's', 'm', false],
        [68,  'Er', '鉺', 's', 'm', false],
        [69,  'Tm', '銩', 's', 'm', false],
        [70,  'Yb', '鐿', 's', 'm', false],
        [71,  'Lu', '鎦', 's', 'm', false],
        [72,  'Hf', '鉿', 's', 'm', false],
        [73,  'Ta', '鉭', 's', 'm', false],
        [74,  'W',  '鎢', 's', 'm', false],
        [75,  'Re', '錸', 's', 'm', false],
        [76,  'Os', '鋨', 's', 'm', false],
        [77,  'Ir', '銥', 's', 'm', false],
        [78,  'Pt', '鉑', 's', 'm', false],
        [79,  'Au', '金', 's', 'm', false],
        [80,  'Hg', '汞', 'l', 'm', false],
        [81,  'Tl', '鉈', 's', 'm', false],
        [82,  'Pb', '鉛', 's', 'm', false],
        [83,  'Bi', '鉍', 's', 'm', false],
        [84,  'Po', '釙', 's', 'm', true],
        [85,  'At', '砈', 's', 'n', true],
        [86,  'Rn', '氡', 'g', 'n', true],
        [87,  'Fr', '鍅', 's', 'm', true],
        [88,  'Ra', '鐳', 's', 'm', true],
        [89,  'Ac', '錒', 's', 'm', true],
        [90,  'Th', '釷', 's', 'm', false],
        [91,  'Pa', '鏷', 's', 'm', true],
        [92,  'U',  '鈾', 's', 'm', false],
        [93,  'Np', '錼', 's', 'm', true],
        [94,  'Pu', '鈽', 's', 'm', false],
        [95,  'Am', '鋂', 's', 'm', true],
        [96,  'Cm', '鋦', 's', 'm', true],
        [97,  'Bk', '鉳', 's', 'm', true],
        [98,  'Cf', '鉲', 's', 'm', true],
        [99,  'Es', '鑀', 's', 'm', true],
        [100, 'Fm', '鐨', 'u', 'm', true],
        [101, 'Md', '鍆', 'u', 'm', true],
        [102, 'No', '鍩', 'u', 'm', true],
        [103, 'Lr', '鐒', 'u', 'm', true],
        [104, 'Rf', '鑪', 'u', 'm', true],
        [105, 'Db', '𨧀', 'u', 'm', true],
        [106, 'Sg', '𨭎', 'u', 'm', true],
        [107, 'Bh', '𨨏', 'u', 'm', true],
        [108, 'Hs', '𨭆', 'u', 'm', true],
        [109, 'Mt', '䥑', 'u', 'u', true],
        [110, 'Ds', '鐽', 'u', 'u', true],
        [111, 'Rg', '錀', 'u', 'u', true],
        [112, 'Cn', '鎶', 'u', 'm', true],
        [113, 'Nh', '',   'u', 'u', true],
        [114, 'Fl', '鈇', 'u', 'm', true],
        [115, 'Mc', '',   'u', 'u', true],
        [116, 'Lv', '鉝', 'u', 'u', true],
        [117, 'Ts', '',   'u', 'u', true],
        [118, 'Og', '',   'u', 'u', true],
    ];

    vm = new Vue({
        el: '#app',
        data: {
            table: table,
            elements: elements,
        },
        methods: {
            metal_type: function (elem) {
                return {'m': 'metal', 'l': 'metalloid', 'n': 'non-metal', 'u': 'unknown-metal'}[elem[4]];
            },
            state: function (elem) {
                return {'g': 'gas', 'l': 'liquid', 's': 'solid', 'u': 'unknown-state'}[elem[3]];
            },
            radiative: function (elem) {
                return elem[5] ? 'radiative' : '';
            }
        }
    });
}
